# Generated by Django 4.0.1 on 2022-01-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_puplished',
            new_name='is_published',
        ),
    ]
